### ISSUE TITLE
add Spring Boot to support standalone usage (without Liferay)

### ISSUE THREAD

**Issue by mathisdt** [fraunhoferfokus/particity#1]
It would be great if Liferay would not be necessary. Spring Boot could be used to [change the generated artifact](http://docs.spring.io/spring-boot/docs/1.2.6.RELEASE/maven-plugin/repackage-mojo.html) and thus make it executable on its own. This way the installation would be much easier.

**Comment by stampedev** [comment]
Well, we decided for Liferay as CMS, since we didn't wanted to reinvent the wheel regarding basic aspects (user/site/permission mgmt, etc.) and we won't abandon it just now that we started ;) 
Besides that, I fear that it would take a great deal of work to get Liferay ready for spring-boot as there might be many side-effects (e.g. filesytem hook for document storage) - same goes for other approaches like using a standalone version of Tomcat/Tomee, JBoss or Glassfish.

And in the end, what would it be good for? For a quick&dirty test-approach, yes. For production - rather not. 
Non the less, you are absolutely right regarding the ease of installation. We definitely have this on our todo with an eye on actual documentation of the setup along with a decent usability. Furthermore, we are looking into the possibility (by means of licensing) of doing a ready-to-use redistribution of Liferay with all modules and sample-data preconfigured.
